import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const host = readFileSync(join(root, 'src', 'dynamic', 'host.js'), 'utf8').trimEnd()
const client = readFileSync(join(root, 'src', 'dynamic', 'client.js'), 'utf8').trimEnd()
const nativeDir = join(root, 'dist', 'native')
const indent = (value, spaces) => value.split('\n').map((line) => ' '.repeat(spaces) + line).join('\n')
const hostBody = host.replaceAll("schema: { type: 'json' }", "schema: { type: 'object', additionalProperties: true }")

const nativeHost = [
  "const DASHBOARD_STATE_PATH = '/dsh-agent-ssh-dashboard/api/state'",
  "const DASHBOARD_TASKS_PATH = '/dsh-agent-ssh-dashboard/api/tasks'",
  "const DASHBOARD_DOWNLOAD_SESSION_PATH = '/dsh-agent-ssh-dashboard/api/download-session'",
  "const DASHBOARD_DOWNLOAD_TASK_PATH = '/dsh-agent-ssh-dashboard/api/download-task'",
  '',
  'function defineTool(options) {',
  '  const properties = {}',
  '  const required = []',
  '  for (const [key, value] of Object.entries(options.parameters)) {',
  '    const { required: isRequired, ...schema } = value',
  '    properties[key] = schema',
  '    if (isRequired) required.push(key)',
  '  }',
  '  return {',
  '    ...options,',
  "    parameters: { type: 'object', properties, required, additionalProperties: false },",
  '  }',
  '}',
  '',
  'function createPlugin(harness) {',
  indent(hostBody, 2),
  '}',
  '',
  'const plugin = createPlugin({})',
  'export const name = plugin.name',
  "export const inject = [...new Set([...plugin.inject, 'webServer'])]",
  '',
  'function registerRoute(ctx, path, handler, label) {',
  '  return ctx.effect(() => ctx.webServer.register({',
  "    kind: 'exact',",
  '    path,',
  '    async handler(req, res) {',
  "      if (req.method !== 'GET') {",
  '        res.writeHead(405)',
  '        res.end()',
  '        return',
  '      }',
  '      try {',
  '        const value = await handler()',
  "        res.writeHead(200, { 'content-type': 'application/json; charset=utf-8' })",
  '        res.end(JSON.stringify(value))',
  '      } catch (error) {',
  "        res.writeHead(500, { 'content-type': 'application/json; charset=utf-8' })",
  "        res.end(JSON.stringify({ error: error instanceof Error ? error.message : String(error) }))",
  '      }',
  '    },',
  '  }), label)',
  '}',
  '',
  'function registerArgRoute(ctx, path, handler, label) {',
  '  return ctx.effect(() => ctx.webServer.register({',
  "    kind: 'exact',",
  '    path,',
  '    async handler(req, res) {',
  "      if (req.method !== 'GET') {",
  '        res.writeHead(405)',
  '        res.end()',
  '        return',
  '      }',
  '      try {',
  "        const url = new URL(req.url, 'http://localhost')",
  "        const arg = url.searchParams.get('id') || url.searchParams.get('session') || url.searchParams.get('task') || undefined",
  '        const value = await handler(arg)',
  "        res.writeHead(200, { 'content-type': 'application/json; charset=utf-8' })",
  '        res.end(JSON.stringify(value))',
  '      } catch (error) {',
  "        res.writeHead(500, { 'content-type': 'application/json; charset=utf-8' })",
  "        res.end(JSON.stringify({ error: error instanceof Error ? error.message : String(error) }))",
  '      }',
  '    },',
  '  }), label)',
  '}',
  '',
  'export function apply(ctx) {',
  '  const harness = {',
  '    defineTool,',
  '    registerTool(_context, tool) {',
  "      return ctx.effect(() => ctx.tools.register(tool), 'dsh-agent-ssh-dashboard: tool ' + tool.name)",
  '    },',
  '    handle(key, handler) {',
  "      if (key === 'dashboard.state') return registerRoute(ctx, DASHBOARD_STATE_PATH, () => handler({}), 'dsh-agent-ssh-dashboard: state')",
  "      if (key === 'dashboard.tasks') return registerArgRoute(ctx, DASHBOARD_TASKS_PATH, (arg) => handler(arg), 'dsh-agent-ssh-dashboard: tasks')",
  "      if (key === 'dashboard.downloadSession') return registerArgRoute(ctx, DASHBOARD_DOWNLOAD_SESSION_PATH, (arg) => handler(arg), 'dsh-agent-ssh-dashboard: downloadSession')",
  "      if (key === 'dashboard.downloadTask') return registerArgRoute(ctx, DASHBOARD_DOWNLOAD_TASK_PATH, (arg) => handler(arg), 'dsh-agent-ssh-dashboard: downloadTask')",
  "      throw new Error('unsupported dashboard handler: ' + key)",
  '    },',
  '  }',
  '  return createPlugin(harness).apply(ctx)',
  '}',
  '',
].join('\n')

const nativeClient = [
  'window.__ModuleLoader__.load({',
  "  id: 'dsh-agent-ssh-dashboard',",
  '  factory: function (require) {',
  '    var module = { exports: {} }',
  "    var React = require('react')",
  '    var styles = {',
  '      insert: function (css) {',
  "        var element = document.createElement('style')",
  "        element.setAttribute('data-dsh-agent-ssh-dashboard', '')",
  '        element.textContent = css',
  '        document.head.appendChild(element)',
  '        return function () { element.remove() }',
  '      },',
  '    }',
  '    var host = {',
  '      call: async function (name, arg) {',
  "        var pathMap = {",
  "          'dashboard.state': '/dsh-agent-ssh-dashboard/api/state',",
  "          'dashboard.tasks': '/dsh-agent-ssh-dashboard/api/tasks',",
  "          'dashboard.downloadSession': '/dsh-agent-ssh-dashboard/api/download-session',",
  "          'dashboard.downloadTask': '/dsh-agent-ssh-dashboard/api/download-task',",
  '        }',
  "        var path = pathMap[name]",
  "        if (path === undefined) throw new Error('unsupported dashboard call: ' + name)",
  "        if (arg !== undefined && arg !== null && typeof arg !== 'object') {",
  "          var separator = path.indexOf('?') >= 0 ? '&' : '?'",
  "          path += separator + 'id=' + encodeURIComponent(String(arg))",
  '        }',
  "        var response = await fetch(path, { cache: 'no-store' })",
  '        var value = await response.json()',
  "        if (!response.ok) throw new Error(value && value.error ? value.error : 'dashboard request failed')",
  '        return value',
  '      },',
  '    }',
  '    function createPlugin() {',
  indent(client, 6),
  '    }',
  '    module.exports = createPlugin()',
  '    return module.exports',
  '  },',
  '})',
  '',
].join('\n')

mkdirSync(nativeDir, { recursive: true })
writeFileSync(join(nativeDir, 'index.js'), nativeHost, 'utf8')
writeFileSync(join(nativeDir, 'client.js'), nativeClient, 'utf8')
console.log('Built native Host/Client package')